### ISSUE TITLE
Unused 'exec' in setup.py?

### ISSUE THREAD

**Issue by jayaddison** [yashsinghcodes/fetch#5]
It might be possible to remove this line? https://github.com/yashsinghcodes/fetch/blob/8df0933e494903c07b96369f0840e57493282cff/setup.py#L12

**Comment by yashsinghcodes** [comment]
Yes, I don't know why i did that but thank you. I have removed the __version__.py and the line for setup.py.

**Comment by jayaddison** [comment]
Cool - no probs, thank you!
